 ---INSERT ADDRESS DETAILS
INSERT INTO ADDRESS 
            (ID,CITY,POSTAL_CODE, ADDRESS_LINE1,ADDRESS_LINE2,SUBURB,LOCATION_PIN) 
     VALUES (1,'JOHANNESBURG','1724','EMILY HOBHOUSE','EMILY HOBHOUSE','HONEYDEW','0000000000000'); 
 
     
---INSERT PERSON DETAILS
INSERT INTO PERSON 
            (ID,CELLPHONE,EMAIL_ADDRESS,NAME,SURNAME,ID_NUMBER,ADDRESS_ID) 
     VALUES (1,'0785151165','achavanga@gmail.com','ABEL', 'CHAVANGA','',(SELECT Max(ID) FROM ADDRESS)); 
     

---INSERT USER DETAILS
INSERT INTO SYS_USER 
            (ID,LAST_SIGNED_IN,PASSWORD,USER_STATUS,USER_TYPE,USER_NAME,PERSON_ID) 
     VALUES (1,'2020-04-20','TEST','ACTIVE','SYS_ADMIN','ABEL',(SELECT Max(ID) FROM PERSON)); 


---INSERT ADDRESS DETAILS
INSERT INTO COMPANY 
            (ID,CELLPHONE,COMPANY_NAME,EMAIL_ADDRESS,PHONE,COMPANY_WEBSITE_URL,CONTACT_PERSON_ID,ADDRESS_ID) 
     VALUES(1,'0785151165','Makro','makro@makro.co.za','0119090054','www',(SELECT Max(ID) FROM PERSON),(SELECT Max(ID) FROM ADDRESS)); 

     
INSERT INTO QUEUE 
            (ID,QUEUE_NUMBER,QUEUE_DATE,QUEUE_STATUS,PROCESSED_DATE,PERSON_ID) 
     VALUES(1,'0000001','2020-05-02 23:03:38','ACTIVE','2020-05-02 23:03:38', (SELECT Max(ID) FROM PERSON));

